services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: directus
      MYSQL_ROOT_PASSWORD: directus
      MYSQL_USER: directus
      MYSQL_PASSWORD: directus
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app-network
    command: >
      --sort_buffer_size=2097152
      --max_sort_length=8192
      --tmp_table_size=268435456
      --max_heap_table_size=268435456
      --innodb_buffer_pool_size=512M

  directus:
    image: directus/directus:latest
    depends_on:
      - db
    ports:
      - "8055:8055"
    env_file:
      - .env
    environment:
      - SECRET=${SECRET}
      - PUBLIC_URL=${PUBLIC_URL}
      - AUTH_TOKEN_TTL=${AUTH_TOKEN_TTL}
      - ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL}
      - REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_CLIENT=${DB_CLIENT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ENABLED=${CORS_ENABLED}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - LOG_LEVEL=${LOG_LEVEL}
      - EXTENSIONS_AUTO_RELOAD=${EXTENSIONS_AUTO_RELOAD}
      # Variables SMTP para invitaciones a workspaces
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_TLS=${SMTP_TLS}
      - SMTP_IGNORE_TLS=${SMTP_IGNORE_TLS}
      # Variables EMAIL para Directus nativo (reset de contraseña)
      - EMAIL_TRANSPORT=${EMAIL_TRANSPORT}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - EMAIL_SMTP_SECURE=${EMAIL_SMTP_SECURE}
      - EMAIL_SMTP_IGNORE_TLS=${EMAIL_SMTP_IGNORE_TLS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - PASSWORD_RESET_URL_ALLOW_LIST=${PASSWORD_RESET_URL_ALLOW_LIST}
      - FILES_MAX_SIZE=${FILES_MAX_SIZE}
      - FILES_MIME_TYPE_ALLOW_LIST=${FILES_MIME_TYPE_ALLOW_LIST}
      - FILES_FOLDER_SIZE_LIMIT=${FILES_FOLDER_SIZE_LIMIT}
      - MAX_PAYLOAD_SIZE=${MAX_PAYLOAD_SIZE}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT}
      - SOCKET_SERVER_URL=http://socket-server:4010
    volumes:
      - directus_data:/data
      - directus_uploads:/directus/uploads
      - ./extensions:/directus/extensions
    restart: unless-stopped
    networks:
      - app-network

  socket-server:
    build:
      context: ./socket-server
    volumes:
      - ./socket-server:/app
    ports:
      - "4010:4010"
    env_file:
      - .env
    environment:
      - SOCKET_SERVER_PORT=${SOCKET_SERVER_PORT}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - directus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  directus_data:
  directus_uploads:
