services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: directus
      MYSQL_ROOT_PASSWORD: directus
      MYSQL_USER: directus
      MYSQL_PASSWORD: directus
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  directus:
    image: directus/directus:latest
    depends_on:
      - db
    ports:
      - "8055:8055"
    env_file:
      - .env
    environment:
      - SECRET=${SECRET}
      - PUBLIC_URL=${PUBLIC_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_CLIENT=${DB_CLIENT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ENABLED=${CORS_ENABLED}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - LOG_LEVEL=${LOG_LEVEL}
      - EXTENSIONS_AUTO_RELOAD=${EXTENSIONS_AUTO_RELOAD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    volumes:
      - directus_data:/data
      - ./extensions:/directus/extensions
    restart: unless-stopped

  socket-server:
    build:
      context: ./socket-server
    volumes:
      - ./socket-server:/app
    ports:
      - "4010:4010"
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - directus

volumes:
  db_data:
  directus_data:
